/*
 * This source file was generated by the Gradle 'init' task
 */
package lab5;

import org.junit.jupiter.api.Test;

import lab5.Cartas.*;
import lab5.Efeitos.*;
import lab5.Entidades.*;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class CartasTest {

    private Heroi heroi;

    @BeforeEach
    void setUp(){
        heroi = new Heroi("Arthur", 40, 0, 10);
    }

    @Test
    void testMortalForca() { /*testando cartas novas*/
        heroi.aplicarEfeito(new Forca("Força explosiva", heroi, 1));
        // Verifica se os atributos foram atribuídos corretamente
        CartaMortalForca mortalForca = new CartaMortalForca("qualquer", "causa (9 vezes força do alvo) de dano e gasta todo o acúmulo de força do alvo / custa 3 de energia", 3);
        
        mortalForca.usar(heroi);
        assertNull(heroi.getForca());
        assertEquals(31, heroi.getVida());
    }

    @Test
    void testCura() { /*testando cartas novas*/
        heroi.receberDano(2);
        // Verifica se os atributos foram atribuídos corretamente
        CartaCura pocao = new CartaCura("poção de cura", "concede 5 de cura / custa 1 energia", 1);
        pocao.usar(heroi);
        assertEquals(40, heroi.getVida());
    }
    @Test
    void testVelocidade() { /*testando cartas novas*/
        // Verifica se os atributos foram atribuídos corretamente
        CartaVelocidade agilidade = new CartaVelocidade("pés ágeis", "concede +2 de velocidade ao alvo / custa 1 energia", 1);
        agilidade.usar(heroi);
        assertEquals(12, heroi.getVelocidade());
    }

    void testDano(){
        CartaDano dano = new CartaDano("qualquer", "qualquer", 2);
        dano.usar(heroi);
        assertEquals(30, heroi.getVida());
    }

    void testEscudo(){
        CartaEscudo escudo = new CartaEscudo("qualquer", "qualquer", 2);
        escudo.usar(heroi);
        assertEquals(10, heroi.getEscudo());
    }

    void testForca(){
        CartaForca forca = new CartaForca(null, null, 1);
        forca.usar(heroi);
        assertEquals(1, heroi.getEfeitos().get(0).getAcumulo());
    }
    void testVeneno(){
        CartaVeneno veneno = new CartaVeneno(null, null, 1);
        veneno.usar(heroi);
        assertEquals(2, heroi.getEfeitos().get(0).getAcumulo());
    }
    void testMortalVeneno(){
        heroi.aplicarEfeito(new Veneno("qualquer", heroi, 1));
        // Verifica se os atributos foram atribuídos corretamente
        CartaMortalVeneno mortalVeneno = new CartaMortalVeneno("qualquer", "qualquer", 2);
        mortalVeneno.usar(heroi);
        assertNull(heroi.getVeneno());
        assertEquals(34, heroi.getVida());
    }

    void testLentidão(){
        CartaLentidao lentidao = new CartaLentidao("qualquer", "qualquer", 1);
        lentidao.usar(heroi);
        assertEquals(8, heroi.getVelocidade());
    }

}